import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home() {

    return ( 
        <div className = {styles.container} >  
            <Head>
                <title>Alliance TCI</title> 
                <meta name = "description"content = "Generated by create next app"/>
                <link rel = "icon" href = "/logotci.png"/>
            </Head>
            <main className = {styles.main}>
                <h1 className = {styles.title}>
                    Bienvenue dans l'alliance{' '}TCI
                </h1>
                <div className = {styles.grid}>
                    <Link href='/imperatrice'>
                        <a className = {styles.card}>
                            <h2> Impératrice &rarr; </h2>
                                <p> Liste User + teams + scores + classement</p>
                        </a>        
                    </Link>
                    <Link href='/temperance'>
                        <a className = {styles.card}>
                            <h2> Tempérance &rarr; </h2>
                                <p> Liste User + teams + scores + classement</p>
                        </a>
                    </Link>
                    <Link href='/equilibrage'>
                        <a className = {styles.card}>
                            <h2> Equilibrage &rarr; </h2> 
                                <p> Users + Position + Boss + Pv + SortBy()</p>
                        </a>
                    </Link>
                    <Link href='/formulaire'>
                        <a className={styles.card}>
                            <h2> Formulaire &rarr; </h2>
                            <p> Users + Position + Boss + Pv + SortBy()</p>
                        </a>
                    </Link>
                    
                    <Link href='/placement'>
                        <a className = {styles.card}>
                            <h2> Placements &rarr; </h2> 
                                <p> Users + teams + scores + dateTime</p>
                        </a>
                    </Link>
                </div> 
            <iframe src="https://discord.com/widget?id=758029805055639782&theme=dark" width="350" height="400" allowtransparency="true" frameBorder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
        </main>
    </div>
    )
}