import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
    return ( 
    <div className = {styles.container} >
        <Head>
            <title>Alliance TCI</title> 
            <meta name = "description"content = "Generated by create next app"/>
            <link rel = "icon" href = "/logotci.png"/>
        </Head>

        <main className = {styles.main}>
            <h1 className = {styles.title}>
                Bienvenue dans l'alliance{' '}TCI
            </h1>
                <p className = {styles.description}>Edit by{' '}
                    <code className = {styles.code}>Sundaday</code>
                </p>
            <div className = {styles.grid}>
                <Link href='/imperatrice'>
                    <a className = {styles.card}>
                        <h2> Impératrice &rarr; </h2>
                            <p> Liste User + teams + scores + classement</p>
                    </a>        
                </Link>
                <Link href='/temperance'>
                    <a className = {styles.card}>
                        <h2> Tempérance &rarr; </h2>
                            <p> Liste User + teams + scores + classement + académie </p>
                    </a>
                </Link>
                <Link href='/equilibrage'>
                    <a className = {styles.card}>
                        <h2> Equilibrage &rarr; </h2> 
                            <p> Users + Position + Boss + Pv + SortBy()</p>
                    </a>
                </Link>
                <Link href='/formulaire'>
                    <a className={styles.card}>
                        <h2> Formulaire &rarr; </h2>
                        <p> Users + Position + Boss + Pv + SortBy()</p>
                    </a>
                </Link>
                
                <Link href='/placement'>
                    <a className = {styles.card}>
                        <h2> Placements &rarr; </h2> 
                            <p> Users + teams + scores + dateTime</p>
                    </a>
                </Link>
                    <iframe src="https://discord.com/widget?id=758029805055639782&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
            </div> 
        </main>

        <footer className = {styles.footer}>
            <a href = "https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target = "_blank"
                rel = "noopener noreferrer">Powered by {' '}
                    <span className = {styles.logo}>
                        <Image 
                            src = "/logotci.png"
                            alt = "Vercel Logo"
                            width = {70}
                            height = {70}
                        /> 
                    </span > 
            </a>    
        </footer > 
    </div>
    )
}